### ISSUE TITLE
ModbusClient() not found in any files

### ISSUE THREAD

**Issue by AlbertHatesCodes** [Cloud-Automation/chrome-modbus#5]
![image](https://user-images.githubusercontent.com/105347737/167797828-c825488c-39d2-4a5c-8516-3aaa897eb106.png)

I can't load the main.js completely .Could Anyone helpe me solve this problem?

**Comment by stefanpoeter** [comment]
Hey @AlbertHatesCodes,

if you post the whole code, maybe I could help.

**Comment by AlbertHatesCodes** [comment]
> Hey @AlbertHatesCodes,
> 
> if you post the whole code, maybe I could help.

@stefanpoeter hello my friend 
The Code I used is the sample01 under the folder examples,
I opened it by VS Code and I run it on the Chrome.
I saw the console indicate that this modbusClient was not import.
Neither do the jquery.min.js and modbus.min.js

I guess I didn't do the process correctly or this example lose some files

**Comment by stefanpoeter** [comment]
This is library is not ment to be executed in a browser. You need to run it with node.js.

**Comment by AlbertHatesCodes** [comment]
Got it !Thank you my friend, it works!
What If I really want to show the Data where I got from Modbus TCP.
How should I do it with Node.js?
Could you give me some suggestions?

**Comment by stefanpoeter** [comment]
There are plenty of tutorials and How-Tos for JavaScript and Node.js that will get you started.
